<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Python Programming - 2101CS405</b></center>
<center><b><h1>Lab - 1</b></center>    
<pre>

### 01) WAP to print “Hello World”

In [ ]:
print("Hello World")

Hello World

02) WAP to print your address i) using single print ii) using multiple print

In [ ]:
print("3- New Shubhash nagar,kothariya main road,Rajkot-2")
print("3- New Shubhash nagar")
print("kothariya main road")
print("Rajkot-2")

3- New Shubhash nagar,kothariya main road,Rajkot-2
3- New Shubhash nagar
kothariya main road
Rajkot-2

### 03) WAP to print addition of 2 numbers (without input function)

In [ ]:
a=3
b=2
c=a+b
print(c)

5

### 04) WAP to calculate and print average of 2 numbers (without input function)

In [ ]:
a=1
b=2
c=(a+b)/2
print("avg: ",c)

avg:  1.5

### 05) WAP to add two number entered by user.

In [ ]:
a=int(input("enter number: "))
b=int(input("enter another number: "))
c=a+b
print("ans: ",c)

enter number: 1
enter another number: 2
ans:  3

### 06) WAP to calculate simple interest.

In [ ]:
p=1000
r=20
t=2
s=(p*r*t)/100
print("simple intrest :",s)

simple intrest : 400.0

### 07) WAP Calculate Area and Circumfrence of Circle

In [ ]:
r=15
circum=2*3.14*r
print("circumfrence: ",circum)
area=3.14*r**2
print("area:",area)

circumfrence:  94.2
area: 706.5

### 08) WAP to print Multiplication table of given number without using loops.

In [ ]:
a=int(input("enter number :"))
print(a,"* 1 =",a*1)
print(a,"* 2 =",a*2)
print(a,"* 3 =",a*3)
print(a,"* 4 =",a*4)
print(a,"* 5 =",a*5)
print(a,"* 6 =",a*6)
print(a,"* 7 =",a*7)
print(a,"* 8 =",a*8)
print(a,"* 9 =",a*9)
print(a,"* 10 =",a*10)

enter number :5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

09) WAP to calculate Area of Triangle (hint: a = h * b * 0.5)

In [ ]:
b=int(input("enter base:"))
h=int(input("enter height:"))
area=0.5*b*h
print("area of triangle: ",area)

enter base:5
enter height:5
area of triangle:  12.5

 10) WAP to convert degree to Fahrenheit and vice versa.

In [ ]:
celsius= float(input("Temperature value in degree Celsius: " ))
Fahrenheit= (celsius * 1.8) + 32
print("celsius :",celsius)
print("Fahrenheit :",Fahrenheit)

Fahrenheit= float(input("Temperature value in Fahrenheit : " ))
celsius=((Fahrenheit-32)*5)/9
print("celsius :",celsius)
print("Fahrenheit :",Fahrenheit)

Temperature value in degree Celsius: 34
celsius : 34.0
Fahrenheit : 93.2
Temperature value in Fahrenheit : 93.2
celsius : 34.0
Fahrenheit : 93.2

11) WAP to calculate total marks and Percentage.

In [ ]:
sub1=int(input("enter marks:"))
sub2=int(input("enter marks:"))
sub3=int(input("enter marks:"))
sub4=int(input("enter marks:"))
sub5=int(input("enter marks:"))
total=(sub1+sub2+sub3+sub4+sub5)
per=total/5
print("total:",total,"and percentage is ",per,"%")

enter marks:100
enter marks:100
enter marks:100
enter marks:100
enter marks:100
total: 500 and percentage is  100.0

12) Compute distance between two points taking input from the user (Pythagorean Theorem).

In [ ]:
a1=int(input("enter point x1: "))
b1=int(input("enter point y1: "))
a2=int(input("enter point x2: "))
b2=int(input("enter point y2: "))
c=((((a2-a1)**2)+((b2-b1)**2))**0.5)
print("distance: ",c)

enter point x1: 4
enter point y1: 0
enter point x2: 6
enter point y2: 6
distance:  6.324555320336759

13) WAP to convert seconds into hours, minutes & seconds and print in HH:MM:SS
[e.g. 10000 seconds mean 2:46:40 (2 Hours, 46 Minutes, 40Seconds)]

In [ ]:
sec=int(input("enter seconds:"))
hour= sec //3600
sec %= 3600
min = sec //60
sec %= 60
print(hour,":",min,":",sec)

enter seconds:10000
2 : 46 : 40

### 14) WAP to enter distance into kilometer and convert it into meter, feet,inches, and centimeter

In [ ]:
km=int(input("enter kilometers:"))
m=km*1000
print("meter =",m)
feet=km*3280.84
print("feet =",feet)
inch=km*39370.08
print("inch =",inch)
cm=km*100000
print("cm =",cm)

enter kilometers:1
meter = 1000
feet = 3280.84
inch = 39370.08
cm = 100000